# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /opt/stack/github/ml

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /opt/stack/github/ml

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /opt/stack/github/ml/CMakeFiles /opt/stack/github/ml/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /opt/stack/github/ml/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ml

# Build rule for target.
ml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ml
.PHONY : ml

# fast build rule for target.
ml/fast:
	$(MAKE) -f CMakeFiles/ml.dir/build.make CMakeFiles/ml.dir/build
.PHONY : ml/fast

src/builtin.o: src/builtin.c.o
.PHONY : src/builtin.o

# target to build an object file
src/builtin.c.o:
	$(MAKE) -f CMakeFiles/ml.dir/build.make CMakeFiles/ml.dir/src/builtin.c.o
.PHONY : src/builtin.c.o

src/builtin.i: src/builtin.c.i
.PHONY : src/builtin.i

# target to preprocess a source file
src/builtin.c.i:
	$(MAKE) -f CMakeFiles/ml.dir/build.make CMakeFiles/ml.dir/src/builtin.c.i
.PHONY : src/builtin.c.i

src/builtin.s: src/builtin.c.s
.PHONY : src/builtin.s

# target to generate assembly for a file
src/builtin.c.s:
	$(MAKE) -f CMakeFiles/ml.dir/build.make CMakeFiles/ml.dir/src/builtin.c.s
.PHONY : src/builtin.c.s

src/evaluation.o: src/evaluation.c.o
.PHONY : src/evaluation.o

# target to build an object file
src/evaluation.c.o:
	$(MAKE) -f CMakeFiles/ml.dir/build.make CMakeFiles/ml.dir/src/evaluation.c.o
.PHONY : src/evaluation.c.o

src/evaluation.i: src/evaluation.c.i
.PHONY : src/evaluation.i

# target to preprocess a source file
src/evaluation.c.i:
	$(MAKE) -f CMakeFiles/ml.dir/build.make CMakeFiles/ml.dir/src/evaluation.c.i
.PHONY : src/evaluation.c.i

src/evaluation.s: src/evaluation.c.s
.PHONY : src/evaluation.s

# target to generate assembly for a file
src/evaluation.c.s:
	$(MAKE) -f CMakeFiles/ml.dir/build.make CMakeFiles/ml.dir/src/evaluation.c.s
.PHONY : src/evaluation.c.s

src/ml.o: src/ml.c.o
.PHONY : src/ml.o

# target to build an object file
src/ml.c.o:
	$(MAKE) -f CMakeFiles/ml.dir/build.make CMakeFiles/ml.dir/src/ml.c.o
.PHONY : src/ml.c.o

src/ml.i: src/ml.c.i
.PHONY : src/ml.i

# target to preprocess a source file
src/ml.c.i:
	$(MAKE) -f CMakeFiles/ml.dir/build.make CMakeFiles/ml.dir/src/ml.c.i
.PHONY : src/ml.c.i

src/ml.s: src/ml.c.s
.PHONY : src/ml.s

# target to generate assembly for a file
src/ml.c.s:
	$(MAKE) -f CMakeFiles/ml.dir/build.make CMakeFiles/ml.dir/src/ml.c.s
.PHONY : src/ml.c.s

src/mpc.o: src/mpc.c.o
.PHONY : src/mpc.o

# target to build an object file
src/mpc.c.o:
	$(MAKE) -f CMakeFiles/ml.dir/build.make CMakeFiles/ml.dir/src/mpc.c.o
.PHONY : src/mpc.c.o

src/mpc.i: src/mpc.c.i
.PHONY : src/mpc.i

# target to preprocess a source file
src/mpc.c.i:
	$(MAKE) -f CMakeFiles/ml.dir/build.make CMakeFiles/ml.dir/src/mpc.c.i
.PHONY : src/mpc.c.i

src/mpc.s: src/mpc.c.s
.PHONY : src/mpc.s

# target to generate assembly for a file
src/mpc.c.s:
	$(MAKE) -f CMakeFiles/ml.dir/build.make CMakeFiles/ml.dir/src/mpc.c.s
.PHONY : src/mpc.c.s

src/parsing.o: src/parsing.c.o
.PHONY : src/parsing.o

# target to build an object file
src/parsing.c.o:
	$(MAKE) -f CMakeFiles/ml.dir/build.make CMakeFiles/ml.dir/src/parsing.c.o
.PHONY : src/parsing.c.o

src/parsing.i: src/parsing.c.i
.PHONY : src/parsing.i

# target to preprocess a source file
src/parsing.c.i:
	$(MAKE) -f CMakeFiles/ml.dir/build.make CMakeFiles/ml.dir/src/parsing.c.i
.PHONY : src/parsing.c.i

src/parsing.s: src/parsing.c.s
.PHONY : src/parsing.s

# target to generate assembly for a file
src/parsing.c.s:
	$(MAKE) -f CMakeFiles/ml.dir/build.make CMakeFiles/ml.dir/src/parsing.c.s
.PHONY : src/parsing.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... ml"
	@echo "... rebuild_cache"
	@echo "... src/builtin.o"
	@echo "... src/builtin.i"
	@echo "... src/builtin.s"
	@echo "... src/evaluation.o"
	@echo "... src/evaluation.i"
	@echo "... src/evaluation.s"
	@echo "... src/ml.o"
	@echo "... src/ml.i"
	@echo "... src/ml.s"
	@echo "... src/mpc.o"
	@echo "... src/mpc.i"
	@echo "... src/mpc.s"
	@echo "... src/parsing.o"
	@echo "... src/parsing.i"
	@echo "... src/parsing.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

