# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /opt/stack/github/ml

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /opt/stack/github/ml

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /opt/stack/github/ml/CMakeFiles /opt/stack/github/ml/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /opt/stack/github/ml/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ml

# Build rule for target.
ml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ml
.PHONY : ml

# fast build rule for target.
ml/fast:
	$(MAKE) -f CMakeFiles/ml.dir/build.make CMakeFiles/ml.dir/build
.PHONY : ml/fast

error.o: error.c.o
.PHONY : error.o

# target to build an object file
error.c.o:
	$(MAKE) -f CMakeFiles/ml.dir/build.make CMakeFiles/ml.dir/error.c.o
.PHONY : error.c.o

error.i: error.c.i
.PHONY : error.i

# target to preprocess a source file
error.c.i:
	$(MAKE) -f CMakeFiles/ml.dir/build.make CMakeFiles/ml.dir/error.c.i
.PHONY : error.c.i

error.s: error.c.s
.PHONY : error.s

# target to generate assembly for a file
error.c.s:
	$(MAKE) -f CMakeFiles/ml.dir/build.make CMakeFiles/ml.dir/error.c.s
.PHONY : error.c.s

evaluation.o: evaluation.c.o
.PHONY : evaluation.o

# target to build an object file
evaluation.c.o:
	$(MAKE) -f CMakeFiles/ml.dir/build.make CMakeFiles/ml.dir/evaluation.c.o
.PHONY : evaluation.c.o

evaluation.i: evaluation.c.i
.PHONY : evaluation.i

# target to preprocess a source file
evaluation.c.i:
	$(MAKE) -f CMakeFiles/ml.dir/build.make CMakeFiles/ml.dir/evaluation.c.i
.PHONY : evaluation.c.i

evaluation.s: evaluation.c.s
.PHONY : evaluation.s

# target to generate assembly for a file
evaluation.c.s:
	$(MAKE) -f CMakeFiles/ml.dir/build.make CMakeFiles/ml.dir/evaluation.c.s
.PHONY : evaluation.c.s

ml.o: ml.c.o
.PHONY : ml.o

# target to build an object file
ml.c.o:
	$(MAKE) -f CMakeFiles/ml.dir/build.make CMakeFiles/ml.dir/ml.c.o
.PHONY : ml.c.o

ml.i: ml.c.i
.PHONY : ml.i

# target to preprocess a source file
ml.c.i:
	$(MAKE) -f CMakeFiles/ml.dir/build.make CMakeFiles/ml.dir/ml.c.i
.PHONY : ml.c.i

ml.s: ml.c.s
.PHONY : ml.s

# target to generate assembly for a file
ml.c.s:
	$(MAKE) -f CMakeFiles/ml.dir/build.make CMakeFiles/ml.dir/ml.c.s
.PHONY : ml.c.s

mpc.o: mpc.c.o
.PHONY : mpc.o

# target to build an object file
mpc.c.o:
	$(MAKE) -f CMakeFiles/ml.dir/build.make CMakeFiles/ml.dir/mpc.c.o
.PHONY : mpc.c.o

mpc.i: mpc.c.i
.PHONY : mpc.i

# target to preprocess a source file
mpc.c.i:
	$(MAKE) -f CMakeFiles/ml.dir/build.make CMakeFiles/ml.dir/mpc.c.i
.PHONY : mpc.c.i

mpc.s: mpc.c.s
.PHONY : mpc.s

# target to generate assembly for a file
mpc.c.s:
	$(MAKE) -f CMakeFiles/ml.dir/build.make CMakeFiles/ml.dir/mpc.c.s
.PHONY : mpc.c.s

parsing.o: parsing.c.o
.PHONY : parsing.o

# target to build an object file
parsing.c.o:
	$(MAKE) -f CMakeFiles/ml.dir/build.make CMakeFiles/ml.dir/parsing.c.o
.PHONY : parsing.c.o

parsing.i: parsing.c.i
.PHONY : parsing.i

# target to preprocess a source file
parsing.c.i:
	$(MAKE) -f CMakeFiles/ml.dir/build.make CMakeFiles/ml.dir/parsing.c.i
.PHONY : parsing.c.i

parsing.s: parsing.c.s
.PHONY : parsing.s

# target to generate assembly for a file
parsing.c.s:
	$(MAKE) -f CMakeFiles/ml.dir/build.make CMakeFiles/ml.dir/parsing.c.s
.PHONY : parsing.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... ml"
	@echo "... rebuild_cache"
	@echo "... error.o"
	@echo "... error.i"
	@echo "... error.s"
	@echo "... evaluation.o"
	@echo "... evaluation.i"
	@echo "... evaluation.s"
	@echo "... ml.o"
	@echo "... ml.i"
	@echo "... ml.s"
	@echo "... mpc.o"
	@echo "... mpc.i"
	@echo "... mpc.s"
	@echo "... parsing.o"
	@echo "... parsing.i"
	@echo "... parsing.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

